name: Deploy module

on:
  push:
    branches: [dev]
    paths:
      - 'modules/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v33
        with:
          files: |
            modules/**
          dir_names: 'true'
      - name: Install hs
        run: npm install -g @hubspot/cli
      - name: Create config from secrets
        run: |
          echo "$HUB_CONFIG" >> hubspot.config.yml
        shell: bash
        env:
          HUB_CONFIG: ${{secrets.HUB_CONFIG}}
      - name: Execute script on files
        run: |
          node ./scripts/deploy-modules.js dev ${{ steps.changed-files.outputs.all_changed_files }}